version: 0.2

env:
  variables:
    REPO_NAME: "ocr-lambda"
  exported-variables:
    - IMAGE_URI
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - AWS_REGION=${AWS_REGION:-$AWS_DEFAULT_REGION}
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_URI}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - echo "Using tag: $IMAGE_TAG"
  build:
    commands:
      - echo "Build started on $(date)"
      - docker build --platform linux/amd64 -t ${ECR_URI}/${REPO_NAME}:${IMAGE_TAG} .
  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push ${ECR_URI}/${REPO_NAME}:${IMAGE_TAG}
      - IMAGE_URI=${ECR_URI}/${REPO_NAME}:${IMAGE_TAG}
      - echo "IMAGE_URI=$IMAGE_URI" > imageDetail.txt
      - printf '{"ImageURI":"%s"}' "$IMAGE_URI" > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - imageDetail.txt
